extends:
  - prettier
  - plugin:import/errors
  - plugin:import/warnings

plugins:
  - prettier
  - import

env:
  es6: true
  node: true

rules:
  prettier/prettier: warn
  import/order:
    - warn
    - newlines-between: always